msa_requests = ['Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “gap”: A communication gap starts when we stop receiving messages from a vessel. We would like to distinguish the cases where a communication gap starts (i) near some port and (ii) far from all ports. A communication gap ends when we resume receiving messages from a vessel.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “highSpeedNearCoast”: This activity starts when a vessel is sailing within a coastal area and its speed surpasses the coastal speed limit. The activity ends when the speed of the vessel becomes less than the coastal speed limit or the vessel exits the coastal area.',
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “trawlSpeed”: The activity starts when the vessel is sailing in a fishing area and its speed is within the expected bounds for a trawling activity. The activity ends when the speed of the vessels falls outside the expected bounds for a trawling activity. When there is a gap in signal transmissions, we can no longer assume that the vessel’s speed remains within the aforementioned bounds.',
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “trawlingMovement”: This activity expresses that the vessel is sailing in a manner that is typical for a trawling activity. The activity starts when the vessel changes its heading while sailing within a fishing area. The activity ends when the vessel leaves the fishing area.',
                 
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “lowSpeed”: The activity starts when the vessel starts moving at a low speed. The activity ends when the vessel stops moving at a low speed. When there is a gap in signal transmissions, we can no longer assume that the vessel continues moving at a low speed.',
                 
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “tuggingSpeed”: The activity starts when the vessel is sailing at a speed that is within the expected bounds for a tugging operation. The activity ends when the vessel is no longer sailing at a speed that is within the expected bounds for a tugging operation. When there is a gap in signal transmissions, we can no longer assume that the vessel’s speed remains within the aforementioned bounds.',
                 
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “sarSpeed”: The activity starts when the speed of the vessel exceeds the minimum expected speed of a vessel that is engaged in a search-and-rescue (SAR) operation. The activity ends when the speed of the vessel falls below the aforementioned minimum speed threshold. When there is a gap in signal transmissions, we can no longer assume that the vessel’s speed remains above the aforementioned threshold.',
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “changingSpeed”: The activity starts when the speed of the vessel starts changing. The activity ends when the speed of the vessel stops changing. When there is a gap in signal transmissions, we can no longer assume that the vessel’s speed is currently changing.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “movingSpeed”: The activity monitors the time periods during which a vessel of a certain type is moving at a speed that is “below” the minimum speed expected for a vessel of this type, “normal”, i.e., within the expected bounds for the speed of a vessel of this type, and “above” the maximum speed expected for a vessel of this type. The activity ends when the speed of the vessel falls below the minimum speed expected for a moving vessel. When there is a gap in signal transmissions, we can no longer assume that the vessel’s speed remains the same.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “trawling”: Trawling is a common fishing method that involves a boat - trawler - pulling a fishing net through the water behind it. Trawling lasts as long as the vessel is sailing in a fishing area, its speed is within the expected bounds for a trawling activity and it is sailing in a manner that is typical for a trawling activity. Trawling activities cannot be arbitrarily brief, i.e., the duration of trawling activities exceeds a minimum temporal threshold.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “anchoredOrMoored”: The activity lasts as long as the vessel is idle in an anchorage area that is far from all ports, or is idle near some port.',
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “tugging”: The activity involves a vessel being pulled or towed by a tugboat. Tugging lasts as long as the two involved vessels, one of which must be a tugboat, are sailing close to each other and their speed falls within the expected bounds for a tugging operation. Tugging operations cannot be arbitrarily brief, i.e., the duration of a tugging operation exceeds a minimum temporal threshold.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “sarMovement”: This activity expresses that the vessel is moving in a manner that is typical for a search-and-rescue (SAR) operation. The activity starts when the vessel changes its speed or its heading. When there is a gap in signal transmissions, we can no longer assume that the vessel keeps moving in a similar fashion.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “pilotOps”: This activity expresses that a highly experienced sailor in navigation in specific areas - a maritime pilot - approaches with a pilot vessel, boards and manoeuvres another vessel through dangerous or congested areas. The activity lasts as long as the two involved vessels, one of which being a pilot vessel, are sailing close to each other, each having a low speed or being idle far from all ports, and are not within a coastal area.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “drifting”: This activity expresses that a vessel is drifting due to sea currents or harsh weather conditions. The activity starts when the angle difference between the actual direction of the vessel and the direction of its bow exceeds a maximum limit, expressing a significant divergence. The activity ends when this angle difference falls below the aforementioned threshold or when the vessel stops moving.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “inSAR”: This activity expresses that the vessel is performing a search-and-rescue (SAR) operation. The activity lasts as long as the vessel is sailing at a speed that is typical for a pilot vessel involved in a SAR operation and the vessel is moving in a manner that is typical for such an operation.', 
                
                'Given a composite activity description, provide the rules in the language of RTEC. You may use the built-in events of RTEC, the MSA events, the MSA input fluents, and the MSA background knowledge predicates. You may also use any of the MSA output fluents that you have already learned.\nComposite Maritime Activity Description - “loitering”: This activity expresses that the vessel is in a particular area for a long period without any evident purpose. The activity lasts as long as the vessel has low speed or is idle far from all ports, and it is not near a coast, it is not anchored, and it is not moored. The activity cannot be arbitrarily brief, i.e., we detect “loitering” when the temporal extent during which the vessel is loafing around exceeds a minimum threshold.'
                
        ]

